### PR TITLE
feat: upgrade apollo gateway to v.16

### PR DESCRIPTION
**Pull request by mrjamesjcho**
Upgrade apollo gateway from 0.11.3 to 0.14.0.

### CODE REVIEW

**Comment by mrjamesjcho** [comment]
I have a server using apollo gateway v0.14.0 and it would be great if I could an updated version of this package.

**Review by barbieri — DISMISSED** [review]
looks good to me, let's wait @cabelitos to have a look as he is the author

**Comment by barbieri** [comment]
btw, seems 0.16 is already out, worth updating to the latest one https://github.com/apollographql/apollo-server/blob/master/packages/apollo-gateway/CHANGELOG.md

**Comment by cabelitos** [comment]
@mrjamesjcho  is it ok if we update to v.16?

**Comment by mrjamesjcho** [comment]
@cabelitos I updated with v.16

**Comment by Tybot204** [comment]
@barbieri @cabelitos Gateway dropped support for Node 10 as of v0.15:
https://www.apollographql.com/docs/apollo-server/federation/managed-federation/

**Comment by barbieri** [comment]
> @barbieri @cabelitos Gateway dropped support for Node 10 as of v0.15:
> https://www.apollographql.com/docs/apollo-server/federation/managed-federation/

yeah, but using that old version is kinda bad nowadays... even the aws/azure runtimes support node-12, also the performance benefits should be something to push for node12.

since this is the gateway, you don't need to port the microservices themselves... shouldn't be an issue.

**Comment by barbieri** [comment]
@mrjamesjcho could you do it in one commit (no -> .14 -> .16) and also change the `.github/workflows/ci.yml` file to remove `10.x` from `node-version`?

**Review by barbieri — APPROVED** [review]
perfect :-)

**Review by cabelitos — APPROVED** [review]

**Pull request merged**
