### PR TITLE
Fix sending custom headers

### PR DESCRIPTION
**Pull request by burn2delete**
This is a supplemental fix for using custom headers

### CODE REVIEW

**Comment by barbieri** [comment]
hi @flyboarder, would you mind adding a test to cover this case so we don't break it again in the future? Also, please rebase on top of #55, then I'll include your code in that upcoming release (testing that branch is also appreciated!)

**Comment by cabelitos** [comment]
@barbieri @flyboarder I would also add E2E tests for that as well.
Since apollo always changes this path, thus forcing us the heavily update this function.

So, covering it with E2E and unit sounds a very good idea.

**Review by amran99 — APPROVED** [review]

**Comment by dominik-myszkowski** [comment]
This is pretty urgent and blocking. Please approve the change and build a new release as soon as possible....

**Review by DDDKnightmare — APPROVED** [review]

**Comment by ccosming** [comment]
What about this PR? is necessary for auth and other stuffs...

Thanks!

**Comment by rebirthtobi** [comment]
Waiting for this PR

**Comment by barbieri** [comment]
@oliveirarleo take a look plz

**Comment by veimox** [comment]
FYI, this PR should not be needed if #66 is merged as they [tackle the same problem](https://github.com/profusion/apollo-federation-file-upload/pull/55/files#diff-2bca1ca8bdf56a344fba817aaa4d1ec21c0a5d6f75470a7b0f0ab93fe34be0c3R207-R216)

**Comment by g7fernandes** [comment]
Merged on 4.1

**Pull request closed without merging**
